apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lakefs
  namespace: lakefs
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
    - host: lakefs.vanir-proxmox.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lakefs
                port:
                  number: 80

