apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/kafka"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse

