apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: servicemonitors
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/monitoring/servicemonitors
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse
  dependsOn:
    - name: prometheus-helm-release

