apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: spark
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/spark/helm-release
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-lakehouse
  dependsOn:
    - name: sealed-secrets

